using System.Globalization;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;
using PCConnect.Core;
using PCConnect.Core.Contracts;
using PCConnect.Core.Domain;
using PCConnect.Infrastructure.Contexts.Devices;
using PCConnect.Infrastructure.Contexts.Identity;
using PCConnect.Infrastructure.Data;
using PCConnect.Infrastructure.Security;
using PCConnect.Infrastructure.Telemetry;

namespace PCConnect.Infrastructure.Contexts.Commands;

/// <summary>
/// The commands bounded context: issue, deliver, acknowledge, expire, audit.
///
/// This is the file where a mistake powers off the wrong computer, so the five
/// server-side checks of 03 §3 appear here in order and nowhere else, and every
/// status transition writes its audit row in the same transaction.
/// </summary>
public sealed class CommandService(
    Db db,
    IClock clock,
    RateLimiter limiter,
    IRealtimeNotifier realtime,
    StepUpService stepUp,
    CommandMetrics metrics,
    ILogger<CommandService> logger)
{
    private const int MaxPageSize = 100;

    // ── issue ────────────────────────────────────────────────────────────────

    public async Task<(CommandResponse Command, bool Created)> IssueAsync(
        CallerIdentity caller, IssueCommandRequest request, RequestContext ctx, CancellationToken ct = default)
    {
        // 1. AUTHENTICATE — done by the middleware before this is reached.
        // 2. SCOPE
        caller.Require(Scopes.CommandIssue);

        if (!Guid.TryParse(request.Id, out var commandPublicId))
        {
            throw AppException.Validation("id must be a UUID generated by the client.",
                new ErrorDetail("id", "format"));
        }

        if (!Guid.TryParse(request.DeviceId, out var devicePublicId))
        {
            throw AppException.Validation("deviceId must be a UUID.", new ErrorDetail("deviceId", "format"));
        }

        if (!CommandTypes.TryNormalise(request.Type, out var commandType))
        {
            throw AppException.Validation(
                $"'{request.Type}' is not a supported command type.",
                new ErrorDetail("type", "unsupported"));
        }

        var ttl = CommandTtl.Resolve(request.TtlSeconds);
        var riskTier = CommandTypes.RiskTierFor(commandType);

        // 5. RATE — before the step-up round trip, so a flood costs an attacker a
        // 429 rather than a queue of pending confirmations.
        await limiter.ConsumeAsync(RateBudgets.CommandPerUser, caller.UserId.ToString(CultureInfo.InvariantCulture), ct);
        await limiter.ConsumeAsync(RateBudgets.CommandPerDevice, devicePublicId.ToString(), ct);

        if (riskTier == RiskTiers.Destructive)
        {
            await limiter.ConsumeAsync(RateBudgets.DestructiveCommand, caller.UserId.ToString(CultureInfo.InvariantCulture), ct);
        }

        string? stepUpMethod = null;
        DateTimeOffset? stepUpVerifiedAt = null;

        if (riskTier == RiskTiers.Destructive && caller.ClientKind != ClientKinds.Legacy)
        {
            // ADR-0011: a session alone cannot power a machine off. The legacy
            // shim is the documented exception — its clients cannot present one,
            // and every such command is recorded as unconfirmed.
            stepUpMethod = await stepUp.RedeemAsync(caller, request.StepUpToken, ct);
            stepUpVerifiedAt = clock.UtcNow;
        }
        else if (riskTier == RiskTiers.Destructive)
        {
            stepUpMethod = "legacy_shim";
            stepUpVerifiedAt = clock.UtcNow;
        }

        var result = await db.InTransactionAsync(async (connection, tx) =>
        {
            // Idempotency by construction: a replayed issue with the same
            // client-generated id returns the existing command rather than
            // shutting the machine down twice (02 §3.2).
            var existing = await connection.QuerySingleOrDefaultAsync<CommandRow>(new CommandDefinition(
                CommandSelectSql + " WHERE c.public_id = @PublicId",
                new { PublicId = commandPublicId }, tx, cancellationToken: ct));

            if (existing is not null)
            {
                if (existing.IssuedByUserId != caller.UserId)
                {
                    // Someone else's command id. Same 404 as "no such command":
                    // confirming that an id exists elsewhere is an oracle.
                    throw AppException.NotFound(ErrorCodes.CommandNotFound, "No such command.");
                }

                return (ToResponse(existing, clock.UtcNow), false);
            }

            // 3. OWNERSHIP — resolves the device by authenticated user id.
            var device = await DeviceService.LoadOwnedAsync(connection, tx, caller.UserId, devicePublicId, ct);

            // 4. POLICY — the per-device allow-list, intersected server-side. The
            // agent enforces its own list independently (check 6).
            var allowed = DbJson.StringArray(device.AllowedCommands);
            if (allowed.Count > 0 && !allowed.Contains(commandType, StringComparer.Ordinal))
            {
                throw AppException.Forbidden(ErrorCodes.CommandTypeNotAllowed,
                    $"'{commandType}' is disabled for this device.");
            }

            var issuedAt = clock.UtcNow;
            var expiresAt = issuedAt.Add(ttl);

            long commandId;
            try
            {
                commandId = await connection.ExecuteScalarAsync<long>(new CommandDefinition("""
                    INSERT INTO commands
                        (public_id, device_id, issued_by_user_id, issued_by_client, command_type, params,
                         risk_tier, step_up_verified_at, step_up_method, status, issued_at, expires_at)
                    VALUES
                        (@PublicId, @DeviceId, @UserId, @Client, @Type, @Params::jsonb,
                         @RiskTier, @StepUpAt, @StepUpMethod, 'issued', @IssuedAt, @ExpiresAt)
                    RETURNING id
                    """,
                    new
                    {
                        PublicId = commandPublicId,
                        DeviceId = device.Id,
                        UserId = caller.UserId,
                        Client = ClientToIssuer(caller.ClientKind),
                        Type = commandType,
                        Params = request.Params is null ? null : DbJson.Serialise(request.Params),
                        RiskTier = riskTier,
                        StepUpAt = stepUpVerifiedAt,
                        StepUpMethod = stepUpMethod,
                        IssuedAt = issuedAt,
                        ExpiresAt = expiresAt,
                    }, tx, cancellationToken: ct));
            }
            catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.UniqueViolation)
            {
                // Two concurrent retries of the same id: the loser reads the winner.
                var raced = await connection.QuerySingleAsync<CommandRow>(new CommandDefinition(
                    CommandSelectSql + " WHERE c.public_id = @PublicId",
                    new { PublicId = commandPublicId }, tx, cancellationToken: ct));
                return (ToResponse(raced, clock.UtcNow), false);
            }

            await WriteEventAsync(connection, tx, commandId, CommandEventNames.Issued, "user", ctx,
                new { commandType, riskTier, stepUpMethod }, ct);

            var row = await connection.QuerySingleAsync<CommandRow>(new CommandDefinition(
                CommandSelectSql + " WHERE c.id = @Id", new { Id = commandId }, tx, cancellationToken: ct));

            return (ToResponse(row, clock.UtcNow), true);
        }, ct);

        if (result.Item2)
        {
            metrics.CommandIssued(commandType, riskTier);

            var command = result.Item1;
            await realtime.CommandIssuedAsync(devicePublicId, new PendingCommand(
                command.Id, command.Type, command.Params, command.IssuedAt, command.ExpiresAt, clock.UtcNow), ct);

            await realtime.CommandStatusAsync(caller.UserPublicId,
                new CommandStatusEvent(command.Id, command.DeviceId, command.Status), ct);
        }

        return result;
    }

    // ── read ─────────────────────────────────────────────────────────────────

    public async Task<Page<CommandResponse>> ListAsync(
        CallerIdentity caller, string? cursor, int limit, Guid? deviceFilter, CancellationToken ct = default)
    {
        caller.Require(Scopes.CommandIssue);

        var take = Math.Clamp(limit <= 0 ? 25 : limit, 1, MaxPageSize);
        var before = Cursor.Decode(cursor);

        await using var connection = await db.OpenAsync(ct);
        var rows = (await connection.QueryAsync<CommandRow>(new CommandDefinition(
            CommandSelectSql + """
             WHERE c.issued_by_user_id = @UserId
               AND (@DeviceId::uuid IS NULL OR d.public_id = @DeviceId::uuid)
               AND (@BeforeId::bigint IS NULL OR c.id < @BeforeId::bigint)
             ORDER BY c.id DESC
             LIMIT @Take
            """,
            new
            {
                UserId = caller.UserId,
                DeviceId = deviceFilter,
                BeforeId = before,
                Take = take + 1,
            }, cancellationToken: ct))).ToList();

        var hasMore = rows.Count > take;
        var page = rows.Take(take).ToList();

        return new Page<CommandResponse>(
            page.Select(row => ToResponse(row, clock.UtcNow)).ToList(),
            hasMore ? Cursor.Encode(page[^1].Id) : null);
    }

    public async Task<CommandResponse> GetAsync(CallerIdentity caller, Guid commandId, CancellationToken ct = default)
    {
        caller.Require(Scopes.CommandIssue);

        await using var connection = await db.OpenAsync(ct);
        var row = await connection.QuerySingleOrDefaultAsync<CommandRow>(new CommandDefinition(
            CommandSelectSql + " WHERE c.public_id = @PublicId AND c.issued_by_user_id = @UserId",
            new { PublicId = commandId, UserId = caller.UserId }, cancellationToken: ct));

        return row is null
            ? throw AppException.NotFound(ErrorCodes.CommandNotFound, "No such command.")
            : ToResponse(row, clock.UtcNow);
    }

    public async Task<CommandResponse> CancelAsync(
        CallerIdentity caller, Guid commandId, RequestContext ctx, CancellationToken ct = default)
    {
        caller.Require(Scopes.CommandIssue);

        var response = await db.InTransactionAsync(async (connection, tx) =>
        {
            var row = await connection.QuerySingleOrDefaultAsync<CommandRow>(new CommandDefinition(
                CommandSelectSql + " WHERE c.public_id = @PublicId AND c.issued_by_user_id = @UserId FOR UPDATE OF c",
                new { PublicId = commandId, UserId = caller.UserId }, tx, cancellationToken: ct))
                ?? throw AppException.NotFound(ErrorCodes.CommandNotFound, "No such command.");

            if (!CommandStateMachine.CanTransition(row.Status, CommandStatuses.Cancelled))
            {
                throw AppException.Conflict(ErrorCodes.CommandAlreadyTerminal,
                    $"A command that is '{row.Status}' can no longer be cancelled.");
            }

            await connection.ExecuteAsync(new CommandDefinition("""
                UPDATE commands SET status = 'cancelled', terminal_at = now() WHERE id = @Id
                """, new { row.Id }, tx, cancellationToken: ct));

            await WriteEventAsync(connection, tx, row.Id, CommandEventNames.Cancelled, "user", ctx, null, ct);

            var updated = await connection.QuerySingleAsync<CommandRow>(new CommandDefinition(
                CommandSelectSql + " WHERE c.id = @Id", new { row.Id }, tx, cancellationToken: ct));

            return ToResponse(updated, clock.UtcNow);
        }, ct);

        await realtime.CommandStatusAsync(caller.UserPublicId,
            new CommandStatusEvent(response.Id, response.DeviceId, response.Status), ct);

        return response;
    }

    // ── delivery ─────────────────────────────────────────────────────────────

    /// <summary>
    /// The agent's poll. Selects and marks <c>delivered</c> in one statement, so
    /// a second poll — or a poll racing the push — does not serve the same
    /// command twice (05 §4.3).
    /// </summary>
    public async Task<IReadOnlyList<PendingCommand>> ClaimPendingAsync(
        CallerIdentity caller, RequestContext ctx, CancellationToken ct = default)
    {
        caller.Require(Scopes.CommandReceive);

        if (caller.DeviceId is not { } deviceId)
        {
            throw AppException.Forbidden(ErrorCodes.AuthScopeInsufficient,
                "Only a device token can collect pending commands.");
        }

        var now = clock.UtcNow;

        var claimed = await db.InTransactionAsync(async (connection, tx) =>
        {
            var rows = (await connection.QueryAsync<CommandRow>(new CommandDefinition("""
                WITH claimed AS (
                    UPDATE commands
                       SET status = 'delivered', delivered_at = now()
                     WHERE id IN (
                         SELECT id FROM commands
                          WHERE device_id = @DeviceId
                            AND status = 'issued'
                            AND expires_at > @Now
                          ORDER BY issued_at
                          FOR UPDATE SKIP LOCKED
                     )
                    RETURNING id
                )
                SELECT c.id AS Id, c.public_id AS PublicId, d.public_id AS DevicePublicId,
                       c.issued_by_user_id AS IssuedByUserId, c.command_type AS CommandType, c.params AS Params,
                       c.risk_tier AS RiskTier, c.status, c.issued_at AS IssuedAt, c.expires_at AS ExpiresAt,
                       c.delivered_at AS DeliveredAt, c.acked_at AS AckedAt,
                       c.result_code AS ResultCode, c.result_message AS ResultMessage
                  FROM commands c
                  JOIN claimed ON claimed.id = c.id
                  JOIN devices d ON d.id = c.device_id
                """, new { DeviceId = deviceId, Now = now }, tx, cancellationToken: ct))).ToList();

            foreach (var row in rows)
            {
                await WriteEventAsync(connection, tx, row.Id, CommandEventNames.Delivered, "device", ctx, null, ct);
            }

            return rows;
        }, ct);

        foreach (var row in claimed)
        {
            metrics.CommandDelivered(row.CommandType, clock.UtcNow - row.IssuedAt);
            await realtime.CommandStatusAsync(await ResolveUserPublicIdAsync(row.IssuedByUserId, ct),
                new CommandStatusEvent(row.PublicId.ToString(), row.DevicePublicId.ToString(), CommandStatuses.Delivered), ct);
        }

        return claimed
            .Select(r => new PendingCommand(
                r.PublicId.ToString(), r.CommandType, DbJson.Params(r.Params), r.IssuedAt, r.ExpiresAt, now))
            .ToList();
    }

    /// <summary>
    /// The push half of delivery: the agent confirms it actually received a
    /// command that arrived over the socket.
    ///
    /// 01 section C-3 draws the lifecycle as <c>issued --claim--&gt; delivered</c>,
    /// which was written when the poll was the only way a command reached an
    /// agent. Under the push-first model of 05 a healthy agent never polls, so
    /// every pushed command went straight from <c>issued</c> to a terminal state
    /// and <c>delivered_at</c> stayed null: the "delivered / issued" SLO in 01
    /// section 8 and the funnel in 08 section 4 both measured close to zero
    /// while delivery was in fact working. See 09 section 9.
    ///
    /// The confirmation comes from the agent rather than from the server own
    /// send, because <c>SendAsync</c> returning proves only that the frame was
    /// written to a socket. Claiming delivery on that would be the same class of
    /// lie as the v1 client reporting "Success" for a row it had merely written.
    /// </summary>
    public async Task ConfirmDeliveryAsync(
        CallerIdentity caller, Guid commandId, RequestContext ctx, CancellationToken ct = default)
    {
        caller.Require(Scopes.CommandAck);

        if (caller.DeviceId is not { } deviceId)
        {
            throw AppException.Forbidden(ErrorCodes.AuthScopeInsufficient,
                "Only a device token can confirm delivery.");
        }

        var confirmed = await db.InTransactionAsync(async (connection, tx) =>
        {
            // Narrow on purpose. A command that has already been claimed by a
            // racing poll, acked, cancelled or expired is left exactly as it is,
            // so a duplicate confirmation is a no-op rather than a state change.
            var row = await connection.QuerySingleOrDefaultAsync<CommandRow>(new CommandDefinition("""
                WITH confirmed AS (
                    UPDATE commands
                       SET status = 'delivered', delivered_at = now()
                     WHERE public_id = @PublicId
                       AND device_id = @DeviceId
                       AND status = 'issued'
                       AND expires_at > now()
                    RETURNING id
                )
                SELECT c.id AS Id, c.public_id AS PublicId, d.public_id AS DevicePublicId,
                       c.issued_by_user_id AS IssuedByUserId, c.command_type AS CommandType, c.params AS Params,
                       c.risk_tier AS RiskTier, c.status, c.issued_at AS IssuedAt, c.expires_at AS ExpiresAt,
                       c.delivered_at AS DeliveredAt, c.acked_at AS AckedAt,
                       c.result_code AS ResultCode, c.result_message AS ResultMessage
                  FROM commands c
                  JOIN confirmed ON confirmed.id = c.id
                  JOIN devices d ON d.id = c.device_id
                """, new { PublicId = commandId, DeviceId = deviceId }, tx, cancellationToken: ct));

            if (row is not null)
            {
                await WriteEventAsync(connection, tx, row.Id, CommandEventNames.Delivered, "device", ctx, null, ct);
            }

            return row;
        }, ct);

        if (confirmed is null)
        {
            return;
        }

        metrics.CommandDelivered(confirmed.CommandType, clock.UtcNow - confirmed.IssuedAt);

        await realtime.CommandStatusAsync(await ResolveUserPublicIdAsync(confirmed.IssuedByUserId, ct),
            new CommandStatusEvent(confirmed.PublicId.ToString(), confirmed.DevicePublicId.ToString(),
                CommandStatuses.Delivered), ct);
    }

    /// <summary>
    /// Per-command acknowledgement, replacing "clear the mailbox". This is what
    /// makes push and poll reconcilable (S2-05) and what lets the phone show a
    /// real outcome instead of "Success" meaning "a row was written".
    /// </summary>
    public async Task<CommandResponse> AckAsync(
        CallerIdentity caller, Guid commandId, AckCommandRequest request, RequestContext ctx, CancellationToken ct = default)
    {
        caller.Require(Scopes.CommandAck);

        if (caller.DeviceId is not { } deviceId)
        {
            throw AppException.Forbidden(ErrorCodes.AuthScopeInsufficient, "Only a device token can acknowledge a command.");
        }

        var outcome = (request.Outcome ?? string.Empty).Trim().ToLowerInvariant();
        if (!CommandOutcomes.IsValid(outcome))
        {
            throw AppException.Validation("outcome must be one of ok, error, rejected.",
                new ErrorDetail("outcome", "unsupported"));
        }

        var response = await db.InTransactionAsync(async (connection, tx) =>
        {
            var row = await connection.QuerySingleOrDefaultAsync<CommandRow>(new CommandDefinition(
                CommandSelectSql + " WHERE c.public_id = @PublicId AND c.device_id = @DeviceId FOR UPDATE OF c",
                new { PublicId = commandId, DeviceId = deviceId }, tx, cancellationToken: ct))
                ?? throw AppException.NotFound(ErrorCodes.CommandNotFound, "No such command for this device.");

            var target = CommandOutcomes.ToStatus(outcome);

            if (CommandStatuses.IsTerminal(row.Status))
            {
                // A duplicate ack changes nothing and says so (05 §8).
                throw AppException.Conflict(ErrorCodes.CommandAlreadyTerminal,
                    $"That command is already '{row.Status}'.");
            }

            if (!CommandStateMachine.CanTransition(row.Status, target))
            {
                throw AppException.Conflict(ErrorCodes.CommandAlreadyTerminal,
                    $"A command that is '{row.Status}' cannot become '{target}'.");
            }

            // An ack that arrives after the TTL, reporting success, means an agent
            // executed a stale command. It must never happen; it is recorded and
            // alerted on if it does (05 §9).
            if (outcome == CommandOutcomes.Ok && clock.UtcNow > row.ExpiresAt)
            {
                metrics.StaleExecution(row.CommandType);
                logger.LogError(
                    "Stale execution: command {CommandId} ({Type}) was acked ok at {Now} but expired at {ExpiresAt}",
                    row.PublicId, row.CommandType, clock.UtcNow, row.ExpiresAt);

                await WriteEventAsync(connection, tx, row.Id, CommandEventNames.StaleExecution, "device", ctx,
                    new { expiresAt = row.ExpiresAt, ackedAt = clock.UtcNow }, ct);
            }

            await connection.ExecuteAsync(new CommandDefinition("""
                UPDATE commands
                   SET status = @Status, acked_at = now(), terminal_at = now(),
                       result_code = @ResultCode, result_message = @ResultMessage
                 WHERE id = @Id
                """,
                new
                {
                    Status = target,
                    ResultCode = Truncate(request.ResultCode, 32),
                    ResultMessage = Truncate(request.ResultMessage, 255),
                    row.Id,
                }, tx, cancellationToken: ct));

            await WriteEventAsync(connection, tx, row.Id,
                outcome == CommandOutcomes.Ok ? CommandEventNames.Acked : CommandEventNames.Failed,
                "device", ctx, new { outcome, resultCode = request.ResultCode }, ct);

            var updated = await connection.QuerySingleAsync<CommandRow>(new CommandDefinition(
                CommandSelectSql + " WHERE c.id = @Id", new { row.Id }, tx, cancellationToken: ct));

            return ToResponse(updated, clock.UtcNow);
        }, ct);

        metrics.CommandAcked(response.Type, response.Status);

        await realtime.CommandStatusAsync(caller.UserPublicId,
            new CommandStatusEvent(response.Id, response.DeviceId, response.Status,
                response.ResultCode, response.ResultMessage), ct);

        return response;
    }

    // ── expiry sweep (worker) ────────────────────────────────────────────────

    public sealed record ExpiredCommand(Guid PublicId, Guid DevicePublicId, Guid UserPublicId, string Type);

    /// <summary>
    /// Marks everything past its TTL as expired. Running this is what makes
    /// "never executed after expiry" observable rather than merely intended: a
    /// command that stays <c>issued</c> past its window is a verification
    /// failure (V4), not a quiet backlog.
    /// </summary>
    public async Task<IReadOnlyList<ExpiredCommand>> ExpireDueAsync(int batchSize = 500, CancellationToken ct = default)
    {
        var expired = await db.InTransactionAsync(async (connection, tx) =>
        {
            var rows = (await connection.QueryAsync<ExpiredRow>(new CommandDefinition("""
                WITH due AS (
                    UPDATE commands
                       SET status = 'expired', terminal_at = now()
                     WHERE id IN (
                         SELECT id FROM commands
                          WHERE status IN ('issued','delivered') AND expires_at <= now()
                          ORDER BY expires_at
                          LIMIT @BatchSize
                          FOR UPDATE SKIP LOCKED
                     )
                    RETURNING id, public_id, device_id, issued_by_user_id, command_type
                )
                SELECT due.id AS Id, due.public_id AS PublicId, d.public_id AS DevicePublicId,
                       u.public_id AS UserPublicId, due.command_type AS CommandType
                  FROM due
                  JOIN devices d ON d.id = due.device_id
                  JOIN users u ON u.id = due.issued_by_user_id
                """, new { BatchSize = batchSize }, tx, cancellationToken: ct))).ToList();

            foreach (var row in rows)
            {
                await WriteEventAsync(connection, tx, row.Id, CommandEventNames.Expired, "system",
                    RequestContext.System, null, ct);
            }

            return rows;
        }, ct);

        foreach (var row in expired)
        {
            metrics.CommandExpired(row.CommandType);
            await realtime.CommandStatusAsync(row.UserPublicId,
                new CommandStatusEvent(row.PublicId.ToString(), row.DevicePublicId.ToString(), CommandStatuses.Expired), ct);
        }

        return expired
            .Select(r => new ExpiredCommand(r.PublicId, r.DevicePublicId, r.UserPublicId, r.CommandType))
            .ToList();
    }

    /// <summary>Deletes audit rows past the 90-day retention (01 §6.6).</summary>
    public async Task<int> PurgeOldEventsAsync(int retentionDays = 90, CancellationToken ct = default)
    {
        await using var connection = await db.OpenAsync(ct);
        return await connection.ExecuteAsync(new CommandDefinition("""
            DELETE FROM command_events WHERE occurred_at < now() - make_interval(days => @Days)
            """, new { Days = retentionDays }, cancellationToken: ct));
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    internal const string CommandSelectSql = """
        SELECT c.id AS Id, c.public_id AS PublicId, d.public_id AS DevicePublicId,
               c.issued_by_user_id AS IssuedByUserId, c.command_type AS CommandType, c.params AS Params,
               c.risk_tier AS RiskTier, c.status, c.issued_at AS IssuedAt, c.expires_at AS ExpiresAt,
               c.delivered_at AS DeliveredAt, c.acked_at AS AckedAt,
               c.result_code AS ResultCode, c.result_message AS ResultMessage
          FROM commands c
          JOIN devices d ON d.id = c.device_id
        """;

    private static Task WriteEventAsync(
        NpgsqlConnection connection, NpgsqlTransaction tx, long commandId, string @event, string actor,
        RequestContext ctx, object? detail, CancellationToken ct) =>
        connection.ExecuteAsync(new CommandDefinition("""
            INSERT INTO command_events (command_id, event, actor, actor_ip, detail)
            VALUES (@CommandId, @Event, @Actor, @Ip::inet, @Detail::jsonb)
            """,
            new
            {
                CommandId = commandId,
                Event = @event,
                Actor = actor,
                Ip = ctx.IpAddress,
                Detail = detail is null ? null : DbJson.Serialise(detail),
            }, tx, cancellationToken: ct));

    private async Task<Guid> ResolveUserPublicIdAsync(long userId, CancellationToken ct)
    {
        await using var connection = await db.OpenAsync(ct);
        return await connection.ExecuteScalarAsync<Guid>(new CommandDefinition(
            "SELECT public_id FROM users WHERE id = @Id", new { Id = userId }, cancellationToken: ct));
    }

    /// <summary>
    /// Maps a row for the wire, reporting a command whose TTL has passed as
    /// <c>expired</c> even if the sweep has not written that down yet.
    ///
    /// A command past its <c>expires_at</c> is expired by definition — 01 §C-3
    /// says one not delivered inside its window is never executed — and the
    /// sweep's job is to record that, not to make it true. Reporting the stored
    /// status verbatim meant a phone showed "issued" indefinitely whenever the
    /// worker was not running: the user pressed Lock, nothing happened on the PC,
    /// and the app said the command was still on its way. Forever. That is the
    /// exact failure this system exists to stop — v1's `{"message":"Success"}`
    /// for a row that had merely been written.
    ///
    /// The durable transition, the audit row and the metric still belong to the
    /// worker. This only stops the read path claiming something it can prove is
    /// no longer true.
    /// </summary>
    internal static CommandResponse ToResponse(CommandRow row, DateTimeOffset now) => new(
        row.PublicId.ToString(),
        row.DevicePublicId.ToString(),
        row.CommandType,
        EffectiveStatus(row, now),
        row.RiskTier,
        DbJson.Params(row.Params),
        row.IssuedAt,
        row.ExpiresAt,
        row.DeliveredAt,
        row.AckedAt,
        row.ResultCode,
        row.ResultMessage);

    private static string EffectiveStatus(CommandRow row, DateTimeOffset now) =>
        !CommandStatuses.IsTerminal(row.Status) && row.ExpiresAt <= now
            ? CommandStatuses.Expired
            : row.Status;

    private static string ClientToIssuer(string clientKind) => clientKind switch
    {
        ClientKinds.Legacy => "legacy_shim",
        ClientKinds.DesktopAgent => "desktop",
        ClientKinds.Web => "web",
        _ => "mobile",
    };

    private static string? Truncate(string? value, int max) =>
        value is null ? null : value.Length <= max ? value : value[..max];

    internal sealed record CommandRow
    {
        public long Id { get; init; }
        public Guid PublicId { get; init; }
        public Guid DevicePublicId { get; init; }
        public long IssuedByUserId { get; init; }
        public string CommandType { get; init; } = string.Empty;
        public string? Params { get; init; }
        public string RiskTier { get; init; } = RiskTiers.Standard;
        public string Status { get; init; } = CommandStatuses.Issued;
        public DateTimeOffset IssuedAt { get; init; }
        public DateTimeOffset ExpiresAt { get; init; }
        public DateTimeOffset? DeliveredAt { get; init; }
        public DateTimeOffset? AckedAt { get; init; }
        public string? ResultCode { get; init; }
        public string? ResultMessage { get; init; }
    }

    private sealed record ExpiredRow
    {
        public long Id { get; init; }
        public Guid PublicId { get; init; }
        public Guid DevicePublicId { get; init; }
        public Guid UserPublicId { get; init; }
        public string CommandType { get; init; } = string.Empty;
    }
}

/// <summary>
/// Opaque cursor over the descending id order. Opaque so the shape can change
/// without breaking a client that stored one.
/// </summary>
public static class Cursor
{
    public static string Encode(long id) =>
        Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes($"id:{id}"))
            .TrimEnd('=').Replace('+', '-').Replace('/', '_');

    public static long? Decode(string? cursor)
    {
        if (string.IsNullOrWhiteSpace(cursor))
        {
            return null;
        }

        try
        {
            var normalised = cursor.Replace('-', '+').Replace('_', '/');
            normalised += (normalised.Length % 4) switch { 2 => "==", 3 => "=", _ => string.Empty };
            var decoded = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(normalised));
            return decoded.StartsWith("id:", StringComparison.Ordinal) &&
                   long.TryParse(decoded[3..], CultureInfo.InvariantCulture, out var id)
                ? id
                : throw AppException.Validation("cursor is not valid.", new ErrorDetail("cursor", "format"));
        }
        catch (FormatException)
        {
            throw AppException.Validation("cursor is not valid.", new ErrorDetail("cursor", "format"));
        }
    }
}
