// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSession() {
  return window['go']['app']['App']['ClearSession']();
}

export function ExecuteSystemCommand(arg1) {
  return window['go']['app']['App']['ExecuteSystemCommand'](arg1);
}

export function FrontendReady() {
  return window['go']['app']['App']['FrontendReady']();
}

export function GetCachedReminders() {
  return window['go']['app']['App']['GetCachedReminders']();
}

export function GetConnectionStatus() {
  return window['go']['app']['App']['GetConnectionStatus']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetSession() {
  return window['go']['app']['App']['GetSession']();
}

export function IsAutoStartEnabled() {
  return window['go']['app']['App']['IsAutoStartEnabled']();
}

export function Notify(arg1, arg2) {
  return window['go']['app']['App']['Notify'](arg1, arg2);
}

export function SaveNotificationStyle(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveNotificationStyle'](arg1, arg2, arg3);
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['app']['App']['SetAutoStart'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function SyncReminders(arg1) {
  return window['go']['app']['App']['SyncReminders'](arg1);
}
