// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';
import {reminders} from '../models';

export function ClearSession():Promise<void>;

export function ExecuteSystemCommand(arg1:string):Promise<string>;

export function FrontendReady():Promise<void>;

export function GetCachedReminders():Promise<any>;

export function GetConnectionStatus():Promise<app.ConnectivityState>;

export function GetContext():Promise<context.Context>;

export function GetSession():Promise<app.Session>;

export function IsAutoStartEnabled():Promise<boolean>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function SaveNotificationStyle(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSession(arg1:app.Session):Promise<app.Session>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SyncReminders(arg1:Array<reminders.Reminder>):Promise<void>;
