<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>pcconnect-worker</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PCConnect.Core\PCConnect.Core.csproj" />
    <ProjectReference Include="..\PCConnect.Infrastructure\PCConnect.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Formatting.Compact" />
  </ItemGroup>
</Project>
