using Microsoft.AspNetCore.Mvc;
using PCConnect.Api.Auth;
using PCConnect.Api.Http;
using PCConnect.Core.Contracts;
using PCConnect.Infrastructure.Contexts.Commands;

namespace PCConnect.Api.Endpoints;

public static class CommandEndpoints
{
    public static IEndpointRouteBuilder MapCommandEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/v2/commands").WithTags("Commands");

        group.MapPost("", async (
            IssueCommandRequest request, CommandService commands, HttpContext http, CancellationToken ct) =>
        {
            var (command, created) = await commands.IssueAsync(
                await http.CallerAsync(ct), request, http.RequestContext(), ct);

            // A replayed id returns 200 with the existing command rather than
            // 201: the caller's retry did not create anything (02 §3.2).
            return created
                ? Results.Created($"/v2/commands/{command.Id}", command)
                : Results.Ok(command);
        })
            .RequireAuthorization()
            .WithName("issueCommand")
            .WithSummary("Issue a command to an owned device.")
            .WithDescription(
                "`id` is generated by the client, which makes retry and offline replay idempotent. " +
                "Destructive types (shutdown, restart, signout, hibernate) additionally require a " +
                "`stepUpToken` from /v2/auth/step-up/verify.");

        group.MapGet("", async (
            [FromQuery] string? cursor,
            [FromQuery] int? limit,
            [FromQuery] Guid? deviceId,
            CommandService commands,
            HttpContext http,
            CancellationToken ct) =>
            Results.Ok(await commands.ListAsync(await http.CallerAsync(ct), cursor, limit ?? 25, deviceId, ct)))
            .RequireAuthorization()
            .WithName("listCommands");

        // Ordered before /{commandId} so "pending" is not parsed as an id.
        group.MapGet("/pending", async (CommandService commands, HttpContext http, CancellationToken ct) =>
        {
            var pending = await commands.ClaimPendingAsync(await http.CallerAsync(ct), http.RequestContext(), ct);
            return Results.Ok(new Page<PendingCommand>(pending, null));
        })
            .RequireAuthorization()
            .WithName("claimPendingCommands")
            .WithSummary("Device tokens only. Returns unexpired, undelivered commands and marks them delivered.");

        group.MapGet("/{commandId:guid}", async (
            Guid commandId, CommandService commands, HttpContext http, CancellationToken ct) =>
            Results.Ok(await commands.GetAsync(await http.CallerAsync(ct), commandId, ct)))
            .RequireAuthorization()
            .WithName("getCommand");

        group.MapPost("/{commandId:guid}/cancel", async (
            Guid commandId, CommandService commands, HttpContext http, CancellationToken ct) =>
            Results.Ok(await commands.CancelAsync(await http.CallerAsync(ct), commandId, http.RequestContext(), ct)))
            .RequireAuthorization()
            .WithName("cancelCommand");

        group.MapPost("/{commandId:guid}/ack", async (
            Guid commandId, AckCommandRequest request, CommandService commands, HttpContext http, CancellationToken ct) =>
            Results.Ok(await commands.AckAsync(await http.CallerAsync(ct), commandId, request, http.RequestContext(), ct)))
            .RequireAuthorization()
            .WithName("ackCommand")
            .WithSummary("Device tokens only. Acknowledges one command with its real outcome.");

        return app;
    }
}
